add network foreach cryprto in getPrices
Atayen/API_NODE_SATT pull request #288
Opened 2023-07-13 14:08 UTC by raniamorheg

**Dear team,**

**This PR** introduces an important update to the cryptoDetails variable by adding the networkSupported and contractAddress fields for each cryptocurrency. The information for these fields will be retrieved using the following API endpoint: https://pro-api.coinmarketcap.com/v2/cryptocurrency/info.

The following changes have been made:

**Adding networkSupported and contractAddress Fields**: We have enhanced the cryptoDetails variable by including the networkSupported and contractAddress fields for each cryptocurrency. These fields provide information about the supported network and contract address associated with each cryptocurrency. The data for these fields will be fetched from the specified API endpoint.
Reviewers, please ensure that the networkSupported and contractAddress fields have been successfully added to the cryptoDetails variable by fetching the necessary data from the provided API endpoint. Verify that the information is accurate and aligned with the respective cryptocurrencies. Your feedback, suggestions, and alternative approaches to improve the implementation of these additions are highly appreciated.

Thank you for your time and effort in enhancing the functionality and data representation of our platform.

Best regards,
Rania Morheg

2023-07-13 15:29 UTC, hichri-louay requested changes

2023-07-13 15:29 UTC, hichri-louay commented on web3/wallets.js
> +            results = await Promise.all([ rp.request(options)])
Can you clarify why Promise.all is used here? As I understand, Promise.all is generally used when dealing with multiple promises. However, it seems like we're only making a single request in this instance. If we're only making a single request, we can call this request directly without using Promise.all.

2023-07-13 15:29 UTC, hichri-louay commented on web3/wallets.js
> +     const  result = await results[0].data.data
Consider removing await in this line (539). As I can see from the previous recap of the data at line 533, it seems unnecessary here. The Promise.all is already handling the promise resolution.

2023-07-13 15:29 UTC, hichri-louay commented on web3/wallets.js
>              for (var i = 0; i < token200.length; i++) {
It seems like there are quite a few loop methods within the getPrice function, which might be causing a performance hit, especially when dealing with large data sets. Could you provide more context about the function and the data it's handling? With more information, we can discuss potential ways to refactor the function to make it more efficient. Specifically, we might look at alternatives to the loop methods being used and determine whether we can minimize their usage, or consider different data structures that could provide the same functionality but with better performance.

2023-07-13 15:29 UTC, hichri-louay commented on web3/wallets.js
> +        for (var i = 0; i < idcrypto?.length; i++) {
It seems like there are quite a few loop methods within the getPrice function, which might be causing a performance hit, especially when dealing with large data sets. Could you provide more context about the function and the data it's handling? With more information, we can discuss potential ways to refactor the function to make it more efficient. Specifically, we might look at alternatives to the loop methods being used and determine whether we can minimize their usage, or consider different data structures that could provide the same functionality but with better performance.

2023-07-13 15:29 UTC, hichri-louay commented on web3/wallets.js
>              for (var i = 0; i < priceMap.length; i++) {
It seems like there are quite a few loop methods within the getPrice function, which might be causing a performance hit, especially when dealing with large data sets. Could you provide more context about the function and the data it's handling? With more information, we can discuss potential ways to refactor the function to make it more efficient. Specifically, we might look at alternatives to the loop methods being used and determine whether we can minimize their usage, or consider different data structures that could provide the same functionality but with better performance.

2023-07-13 15:29 UTC, hichri-louay commented on web3/wallets.js
> +             priceMap = response.data.data.map( (elem) => {
It seems like there are quite a few loop methods within the getPrice function, which might be causing a performance hit, especially when dealing with large data sets. Could you provide more context about the function and the data it's handling? With more information, we can discuss potential ways to refactor the function to make it more efficient. Specifically, we might look at alternatives to the loop methods being used and determine whether we can minimize their usage, or consider different data structures that could provide the same functionality but with better performance.

2023-07-21 14:52 UTC, skanderKha approved these changes

2023-07-21 14:52 UTC, skanderKha commented on web3/wallets.js
> +            },
I think it's better to  move the options variable in the config file to make cointMarketCap reusiable for futur needs .

2023-07-24 08:31 UTC, HamdiBenK approved these changes

2023-07-24 08:32 UTC, merged